Revert adding Builder subclasses to unions
Using builder subclasses in unions in Swift-generated code causes
separate errors to be triggered:

Error: Inject method com.facebook.swift.foo is not allowed on struct class, since struct has a builder
Attempted to resolve a recursive reference to type 'com.facebook.swift.foo' before the referenced type was cached (most likely a recursive type support bug)